project_id = "vzkwkcypkfrpfhhsghwn"

[functions.evaluate-service]
verify_jwt = true

[functions.diagnose-transport]
verify_jwt = true

[functions.urban-report-chat]
verify_jwt = true

[functions.recommend-services]
verify_jwt = true