/**
 * Configuração das camadas overlay do GeoSampa (WFS GeoJSON).
 * Usadas para exibir polígonos/linhas no mapa (distritos, subprefeituras, ciclovias, etc).
 *
 * WFS base: https://wfs.geosampa.prefeitura.sp.gov.br/geoserver/geoportal/wfs
 *
 * CORS: GeoSampa não envia Access-Control-Allow-Origin.
 * - Dev: proxy Vite (/geosampa-wfs)
 * - Prod: Edge Function geosampa-wfs-proxy (via CAMARA_URL ou VITE_SUPABASE_URL)
 */
const WFS_ORIGIN = "https://wfs.geosampa.prefeitura.sp.gov.br";
const WFS_QUERY =
  "service=WFS&version=1.0.0&request=GetFeature&outputFormat=application%2Fjson&srsName=EPSG:4326";

const supabaseUrl = (import.meta.env.CAMARA_URL ?? import.meta.env.VITE_SUPABASE_URL) as string | undefined;
const customProxy = import.meta.env.VITE_GEOSAMPA_WFS_PROXY as string | undefined;

/** Proxy em prod: Edge Function ou custom env */
const prodProxyBase = customProxy
  ? customProxy.replace(/\/?$/, "")
  : supabaseUrl
    ? `${supabaseUrl.replace(/\/$/, "")}/functions/v1/geosampa-wfs-proxy`
    : null;

/** Em dev usa proxy Vite; em prod usa Edge Function (ou custom) para evitar CORS */
const WFS_BASE =
  import.meta.env.DEV
    ? `/geosampa-wfs/geoserver/geoportal/wfs?${WFS_QUERY}`
    : prodProxyBase
      ? `${prodProxyBase}?${WFS_QUERY}`
      : `${WFS_ORIGIN}/geoserver/geoportal/wfs?${WFS_QUERY}`;

export interface GeoSampaOverlayLayer {
  id: string;
  typeName: string;
  label: string;
  fillColor?: string;
  strokeColor?: string;
  strokeWeight?: number;
  fillOpacity?: number;
  maxFeatures?: number;
}

export const GEOSAMPA_OVERLAY_LAYERS: GeoSampaOverlayLayer[] = [
  // Limites administrativos
  {
    id: "distrito",
    typeName: "distrito_municipal",
    label: "Distritos",
    fillColor: "#3b82f6",
    fillOpacity: 0.08,
    strokeColor: "#1d4ed8",
    strokeWeight: 1.5,
    maxFeatures: 100,
  },
  {
    id: "subprefeitura",
    typeName: "subprefeitura",
    label: "Subprefeituras",
    fillColor: "#059669",
    fillOpacity: 0.06,
    strokeColor: "#047857",
    strokeWeight: 2,
    maxFeatures: 35,
  },
  // Transporte / mobilidade
  {
    id: "via_bicicleta",
    typeName: "via_bicicleta",
    label: "Ciclovias",
    strokeColor: "#eab308",
    strokeWeight: 3,
    fillColor: "transparent",
    maxFeatures: 500,
  },
  {
    id: "linha_metro",
    typeName: "linha_metro",
    label: "Linhas de Metrô",
    strokeColor: "#dc2626",
    strokeWeight: 3,
    fillColor: "transparent",
    maxFeatures: 50,
  },
  {
    id: "linha_trem",
    typeName: "linha_trem",
    label: "Linhas de Trem/CPTM",
    strokeColor: "#7c3aed",
    strokeWeight: 2.5,
    fillColor: "transparent",
    maxFeatures: 50,
  },
  {
    id: "corredor_onibus",
    typeName: "corredor_onibus",
    label: "Corredores de Ônibus",
    strokeColor: "#ea580c",
    strokeWeight: 2,
    fillColor: "transparent",
    maxFeatures: 100,
  },
  // Sistema viário e acessibilidade (item 11 – calçadas, rotas pedestres)
  {
    id: "calcada",
    typeName: "calcada",
    label: "Calçadas",
    strokeColor: "#0d9488",
    strokeWeight: 2,
    fillColor: "transparent",
    maxFeatures: 500,
  },
  {
    id: "hierarquia_pedestre",
    typeName: "hierarquia_pedestre",
    label: "Hierarquia Pedestre (rotas acessíveis)",
    strokeColor: "#0891b2",
    strokeWeight: 2,
    fillColor: "transparent",
    maxFeatures: 400,
  },
  // Infraestrutura Urbana (item 14)
  {
    id: "lei_melhoramento_viario",
    typeName: "geoconvias_lei_melhoramento_vigente",
    label: "Lei de Melhoramento Viário",
    fillColor: "#78716c",
    fillOpacity: 0.12,
    strokeColor: "#57534e",
    strokeWeight: 1,
    maxFeatures: 200,
  },
  {
    id: "faixa_nao_edificavel",
    typeName: "geoconvias_faixa_nao_edificavel",
    label: "Faixa Não Edificável",
    fillColor: "#44403c",
    fillOpacity: 0.15,
    strokeColor: "#292524",
    strokeWeight: 1,
    maxFeatures: 300,
  },
  {
    id: "geoinfra_obras",
    typeName: "controle_uso_via_publica_geoinfra",
    label: "Geoinfra – Controle de uso de vias públicas (Obras)",
    fillColor: "#15803d",
    fillOpacity: 0.15,
    strokeColor: "#166534",
    strokeWeight: 1,
    maxFeatures: 200,
  },
  {
    id: "reservatorio_amortecimento",
    typeName: "reservatorio_amortecimento",
    label: "Reservatório de Amortecimento (Piscinões)",
    fillColor: "#0ea5e9",
    fillOpacity: 0.2,
    strokeColor: "#0284c7",
    strokeWeight: 1.5,
    maxFeatures: 100,
  },
  {
    id: "reservatorio_amortecimento_ponto",
    typeName: "reservatorio_amortecimento_ponto",
    label: "Reservatório de Amortecimento – Pontos",
    fillColor: "#0891b2",
    fillOpacity: 0.35,
    strokeColor: "#0e7490",
    strokeWeight: 1.5,
    maxFeatures: 100,
  },
  {
    id: "iluminacao_publica",
    typeName: "iluminacao_publica",
    label: "Iluminação Pública – Pontos",
    fillColor: "#eab308",
    fillOpacity: 0.3,
    strokeColor: "#ca8a04",
    strokeWeight: 1.5,
    maxFeatures: 500,
  },
  {
    id: "transpetro_duto",
    typeName: "transpetro_duto",
    label: "Rede Transpetro – Dutos",
    strokeColor: "#ca8a04",
    strokeWeight: 2,
    fillColor: "transparent",
    maxFeatures: 100,
  },
  {
    id: "transpetro_marco",
    typeName: "transpetro_marco",
    label: "Rede Transpetro – Marcos",
    fillColor: "#b45309",
    fillOpacity: 0.3,
    strokeColor: "#92400e",
    strokeWeight: 1.5,
    maxFeatures: 200,
  },
  // Verde e meio ambiente
  {
    id: "parque_unidade_conservacao",
    typeName: "GEOSAMPA_cadparcs_parque_unidade_conservacao",
    label: "Parques e Unidades de Conservação",
    fillColor: "#16a34a",
    fillOpacity: 0.2,
    strokeColor: "#15803d",
    strokeWeight: 1.5,
    maxFeatures: 200,
  },
  {
    id: "praca_largo",
    typeName: "GEOSAMPA_v_praca_largo",
    label: "Praças e Largos",
    fillColor: "#22c55e",
    fillOpacity: 0.15,
    strokeColor: "#16a34a",
    strokeWeight: 1,
    maxFeatures: 500,
  },
  {
    id: "apa",
    typeName: "GEOSAMPA_cadparcs_area_protecao_apa",
    label: "Áreas de Proteção Ambiental (APA)",
    fillColor: "#065f46",
    fillOpacity: 0.12,
    strokeColor: "#047857",
    strokeWeight: 1.5,
    maxFeatures: 50,
  },
  {
    id: "cobertura_vegetal",
    typeName: "cobertura_vegetal",
    label: "Cobertura Vegetal",
    fillColor: "#166534",
    fillOpacity: 0.2,
    strokeColor: "#14532d",
    strokeWeight: 1,
    maxFeatures: 300,
  },
  {
    id: "vegetacao_significativa",
    typeName: "GEOSAMPA_v_cgpabi_vegetacao_significativa",
    label: "Vegetação Significativa",
    fillColor: "#15803d",
    fillOpacity: 0.25,
    strokeColor: "#166534",
    strokeWeight: 1,
    maxFeatures: 200,
  },
  // Patrimônio cultural
  {
    id: "bem_tombado",
    typeName: "patrimonio_cultural_bem_tombado",
    label: "Patrimônio – Bem Tombado",
    fillColor: "#b45309",
    fillOpacity: 0.15,
    strokeColor: "#92400e",
    strokeWeight: 1.5,
    maxFeatures: 200,
  },
  // Água e drenagem
  {
    id: "bacia_hidrografica",
    typeName: "bacia_hidrografica",
    label: "Bacias Hidrográficas",
    fillColor: "#0ea5e9",
    fillOpacity: 0.1,
    strokeColor: "#0284c7",
    strokeWeight: 1.5,
    maxFeatures: 50,
  },
  {
    id: "mancha_inundacao_5",
    typeName: "mancha_inundacao_5",
    label: "Mancha de Inundação (5 anos)",
    fillColor: "#6366f1",
    fillOpacity: 0.2,
    strokeColor: "#4f46e5",
    strokeWeight: 1,
    maxFeatures: 100,
  },
  {
    id: "mancha_inundacao_25",
    typeName: "mancha_inundacao_25",
    label: "Mancha de Inundação (25 anos)",
    fillColor: "#4f46e5",
    fillOpacity: 0.18,
    strokeColor: "#4338ca",
    strokeWeight: 1,
    maxFeatures: 100,
  },
  {
    id: "mancha_inundacao_100",
    typeName: "mancha_inundacao_100",
    label: "Mancha de Inundação (100 anos)",
    fillColor: "#3730a3",
    fillOpacity: 0.15,
    strokeColor: "#312e81",
    strokeWeight: 1,
    maxFeatures: 100,
  },
  // Proteção e Defesa Civil – Áreas de risco e ocorrências
  {
    id: "area_risco_geologico",
    typeName: "area_risco_geologico",
    label: "Risco Geológico",
    fillColor: "#78350f",
    fillOpacity: 0.25,
    strokeColor: "#a16207",
    strokeWeight: 1.5,
    maxFeatures: 200,
  },
  {
    id: "risco_hidrologico",
    typeName: "risco_hidrologico",
    label: "Risco Hidrológico",
    fillColor: "#0369a1",
    fillOpacity: 0.2,
    strokeColor: "#0284c7",
    strokeWeight: 1.5,
    maxFeatures: 200,
  },
  {
    id: "risco_ocorrencia_alagamento",
    typeName: "risco_ocorrencia_alagamento",
    label: "Ocorrências – Alagamento",
    fillColor: "#0ea5e9",
    fillOpacity: 0.25,
    strokeColor: "#0284c7",
    strokeWeight: 1,
    maxFeatures: 300,
  },
  {
    id: "risco_ocorrencia_inundacao",
    typeName: "risco_ocorrencia_inundacao",
    label: "Ocorrências – Inundação",
    fillColor: "#38bdf8",
    fillOpacity: 0.22,
    strokeColor: "#0ea5e9",
    strokeWeight: 1,
    maxFeatures: 300,
  },
  {
    id: "risco_ocorrencia_deslizamento",
    typeName: "risco_ocorrencia_deslizamento",
    label: "Ocorrências – Deslizamento",
    fillColor: "#991b1b",
    fillOpacity: 0.2,
    strokeColor: "#b91c1c",
    strokeWeight: 1,
    maxFeatures: 200,
  },
  {
    id: "risco_ocorrencia_risco_deslizamento",
    typeName: "risco_ocorrencia_risco_deslizamento",
    label: "Ocorrências – Risco de Deslizamento",
    fillColor: "#dc2626",
    fillOpacity: 0.18,
    strokeColor: "#ef4444",
    strokeWeight: 1,
    maxFeatures: 200,
  },
  {
    id: "risco_ocorrencia_queda_arvore",
    typeName: "risco_ocorrencia_queda_arvore",
    label: "Ocorrências – Queda de Árvore",
    fillColor: "#166534",
    fillOpacity: 0.2,
    strokeColor: "#15803d",
    strokeWeight: 1,
    maxFeatures: 300,
  },
  {
    id: "pluviometro",
    typeName: "pluviometro",
    label: "Pluviômetros",
    fillColor: "#0891b2",
    fillOpacity: 0.3,
    strokeColor: "#0e7490",
    strokeWeight: 1.5,
    maxFeatures: 100,
  },
  {
    id: "massa_d_agua",
    typeName: "massa_d_agua",
    label: "Massas d'água",
    fillColor: "#38bdf8",
    fillOpacity: 0.4,
    strokeColor: "#0ea5e9",
    strokeWeight: 1.5,
    maxFeatures: 100,
  },
  // Meio Físico – Hidrografia (item 19)
  {
    id: "represa_nivel_maximo",
    typeName: "represa_nivel_maximo",
    label: "Represa – Nível Máximo",
    fillColor: "#0ea5e9",
    fillOpacity: 0.35,
    strokeColor: "#0284c7",
    strokeWeight: 1.5,
    maxFeatures: 50,
  },
  {
    id: "hidrografia_ilha",
    typeName: "hidrografia_ilha",
    label: "Ilha (Hidrografia)",
    fillColor: "#78716c",
    fillOpacity: 0.25,
    strokeColor: "#57534e",
    strokeWeight: 1,
    maxFeatures: 100,
  },
  // Meio Físico – Topografia
  {
    id: "marco_geodesico",
    typeName: "marco",
    label: "Marco Geodésico",
    fillColor: "#dc2626",
    fillOpacity: 0.4,
    strokeColor: "#b91c1c",
    strokeWeight: 1.5,
    maxFeatures: 200,
  },
  {
    id: "ponto_cotado",
    typeName: "ponto_cotado",
    label: "Ponto cotado",
    fillColor: "#eab308",
    fillOpacity: 0.35,
    strokeColor: "#ca8a04",
    strokeWeight: 1,
    maxFeatures: 500,
  },
  {
    id: "curva_mestra",
    typeName: "curva_mestra",
    label: "Curva Mestra (Topografia)",
    strokeColor: "#dc2626",
    strokeWeight: 1.5,
    fillColor: "transparent",
    maxFeatures: 400,
  },
  {
    id: "curva_intermediaria",
    typeName: "curva_intermediaria",
    label: "Curva Intermediária (Topografia)",
    strokeColor: "#ec4899",
    strokeWeight: 1,
    fillColor: "transparent",
    maxFeatures: 500,
  },
  {
    id: "declividade",
    typeName: "declividade",
    label: "Declividade",
    fillColor: "#22c55e",
    fillOpacity: 0.2,
    strokeColor: "#16a34a",
    strokeWeight: 1,
    maxFeatures: 300,
  },
  {
    id: "apoio_terrestre_2017",
    typeName: "apoio_terrestre_2017",
    label: "Apoio Terrestre 2017",
    fillColor: "#7c3aed",
    fillOpacity: 0.3,
    strokeColor: "#6d28d9",
    strokeWeight: 1,
    maxFeatures: 300,
  },
  {
    id: "apoio_terrestre_2020",
    typeName: "apoio_terrestre_2020",
    label: "Apoio Terrestre 2020",
    fillColor: "#dc2626",
    fillOpacity: 0.3,
    strokeColor: "#b91c1c",
    strokeWeight: 1,
    maxFeatures: 300,
  },
  // Meio Físico – Área de Proteção e Recuperação dos Mananciais
  {
    id: "manancial_juquery",
    typeName: "manancial_juquery",
    label: "Área de Proteção Mananciais – Alto Juquery",
    fillColor: "#059669",
    fillOpacity: 0.15,
    strokeColor: "#047857",
    strokeWeight: 1,
    maxFeatures: 50,
  },
  {
    id: "manancial_guarapiranga",
    typeName: "manancial_guarapiranga",
    label: "Área de Proteção Mananciais – Guarapiranga",
    fillColor: "#0d9488",
    fillOpacity: 0.15,
    strokeColor: "#0f766e",
    strokeWeight: 1,
    maxFeatures: 50,
  },
  {
    id: "manancial_billings",
    typeName: "manancial_billings",
    label: "Área de Proteção Mananciais – Billings",
    fillColor: "#0891b2",
    fillOpacity: 0.15,
    strokeColor: "#0e7490",
    strokeWeight: 1,
    maxFeatures: 50,
  },
  // Meio Físico – Carta Geotécnica
  {
    id: "carta_geotecnica",
    typeName: "carta_geotecnica",
    label: "Carta Geotécnica 2024",
    fillColor: "#78350f",
    fillOpacity: 0.18,
    strokeColor: "#a16207",
    strokeWeight: 1,
    maxFeatures: 300,
  },
  {
    id: "solo_mole",
    typeName: "solo_mole",
    label: "Solo Mole (Carta Geotécnica)",
    fillColor: "#92400e",
    fillOpacity: 0.2,
    strokeColor: "#b45309",
    strokeWeight: 1,
    maxFeatures: 200,
  },
  // População e habitação
  {
    id: "setor_censitario",
    typeName: "setor_censitario_2022",
    label: "Setores Censitários",
    fillColor: "#a855f7",
    fillOpacity: 0.06,
    strokeColor: "#9333ea",
    strokeWeight: 0.5,
    maxFeatures: 200,
  },
  {
    id: "favela",
    typeName: "geohabisp_vw_wfs_favela_geosampa",
    label: "Favelas",
    fillColor: "#991b1b",
    fillOpacity: 0.15,
    strokeColor: "#b91c1c",
    strokeWeight: 1,
    maxFeatures: 200,
  },
  {
    id: "nucleo",
    typeName: "geohabisp_vw_wfs_nucleo_geosampa",
    label: "Núcleos Habitacionais",
    fillColor: "#c2410c",
    fillOpacity: 0.12,
    strokeColor: "#ea580c",
    strokeWeight: 1,
    maxFeatures: 150,
  },
  // Habitação – HIS, COHAB, conjuntos (item 10)
  {
    id: "habitacao_popular",
    typeName: "habitacao_popular",
    label: "Habitação Popular",
    fillColor: "#b45309",
    fillOpacity: 0.15,
    strokeColor: "#92400e",
    strokeWeight: 1,
    maxFeatures: 200,
  },
  {
    id: "conjunto_habitacional",
    typeName: "habita2geosampa_wfs_conjhabitacional2geosampa_ext",
    label: "Conjunto Habitacional",
    fillColor: "#c2410c",
    fillOpacity: 0.12,
    strokeColor: "#ea580c",
    strokeWeight: 1,
    maxFeatures: 150,
  },
  {
    id: "obra_urbanizacao",
    typeName: "habita2geosampa_wfs_obraurbanizacao2geosampa_ext",
    label: "Obra de Urbanização (assentamentos)",
    fillColor: "#a16207",
    fillOpacity: 0.12,
    strokeColor: "#ca8a04",
    strokeWeight: 1,
    maxFeatures: 150,
  },
  // Rural (item 20) – Unidades de Produção Agropecuária
  {
    id: "unidade_produtiva_rural",
    typeName: "unidade_produtiva_rural",
    label: "Unidades de Produção Agropecuária",
    fillColor: "#22c55e",
    fillOpacity: 0.15,
    strokeColor: "#16a34a",
    strokeWeight: 1,
    maxFeatures: 200,
  },
  // Legislação Urbana
  // Zoneamento (LPUOS)
  {
    id: "zoneamento_2016",
    typeName: "zoneamento_2016_map1",
    label: "Zoneamento 2016 (LPUOS)",
    fillColor: "#6b7280",
    fillOpacity: 0.12,
    strokeColor: "#4b5563",
    strokeWeight: 1,
    maxFeatures: 500,
  },
  {
    id: "zoneamento_classificacao_viaria",
    typeName: "zoneamento_classificacao_viaria",
    label: "Zoneamento – Classificação Viária",
    fillColor: "#78716c",
    fillOpacity: 0.1,
    strokeColor: "#57534e",
    strokeWeight: 1,
    maxFeatures: 300,
  },
  {
    id: "zoneamento_corredor_uso",
    typeName: "zoneamento_corredor_uso",
    label: "Zoneamento – Corredor de Uso",
    fillColor: "#71717a",
    fillOpacity: 0.1,
    strokeColor: "#52525b",
    strokeWeight: 1,
    maxFeatures: 200,
  },
  {
    id: "zoneamento_geoambiental",
    typeName: "GEOSAMPA_zoneamento_geoambiental_apa_cm",
    label: "Zoneamento Geoambiental APA/CM",
    fillColor: "#166534",
    fillOpacity: 0.15,
    strokeColor: "#14532d",
    strokeWeight: 1,
    maxFeatures: 100,
  },
  {
    id: "zoneamento_revogado_lei13885",
    typeName: "perimetro_zoneamento_revogado_lei13885",
    label: "Zoneamento Revogado (Lei 13.885/04)",
    fillColor: "#991b1b",
    fillOpacity: 0.08,
    strokeColor: "#b91c1c",
    strokeWeight: 1,
    maxFeatures: 100,
  },
  // PDE (Plano Diretor)
  {
    id: "pde_zeis",
    typeName: "pde2014_v_zeis_04_map",
    label: "PDE – ZEIS (Zonas Especiais)",
    fillColor: "#a16207",
    fillOpacity: 0.15,
    strokeColor: "#ca8a04",
    strokeWeight: 1,
    maxFeatures: 200,
  },
  {
    id: "pde_macroarea",
    typeName: "pde2014_v_mcrar_02_map",
    label: "PDE – Macroáreas",
    fillColor: "#6366f1",
    fillOpacity: 0.1,
    strokeColor: "#4f46e5",
    strokeWeight: 1,
    maxFeatures: 50,
  },
  {
    id: "plano_acao_regional",
    typeName: "plano_acao_regional",
    label: "Planos Regionais – Ação Regional",
    fillColor: "#7c3aed",
    fillOpacity: 0.1,
    strokeColor: "#6d28d9",
    strokeWeight: 1.5,
    maxFeatures: 100,
  },
  {
    id: "plano_macro_regional",
    typeName: "plano_macro_regional",
    label: "Planos Regionais – Macro Regional",
    fillColor: "#9333ea",
    fillOpacity: 0.08,
    strokeColor: "#7e22ce",
    strokeWeight: 1.5,
    maxFeatures: 50,
  },
  // Operações Urbanas
  {
    id: "operacao_urbana",
    typeName: "operacao_urbana",
    label: "Operações Urbanas",
    fillColor: "#7c2d12",
    fillOpacity: 0.1,
    strokeColor: "#9a3412",
    strokeWeight: 2,
    maxFeatures: 50,
  },
  {
    id: "subsetor_operacao_urbana",
    typeName: "subsetor_operacao_urbana",
    label: "Setores / Subsetores Operação Urbana",
    fillColor: "#9a3412",
    fillOpacity: 0.12,
    strokeColor: "#c2410c",
    strokeWeight: 1.5,
    maxFeatures: 100,
  },
  {
    id: "oucfl_area_influencia",
    typeName: "oucfl_area_influencia",
    label: "Áreas de Influência OUC Faria Lima",
    fillColor: "#b45309",
    fillOpacity: 0.12,
    strokeColor: "#d97706",
    strokeWeight: 1.5,
    maxFeatures: 50,
  },
  // AIU (Áreas de Intervenção Urbana)
  {
    id: "perimetro_aiu",
    typeName: "perimetro_aiu",
    label: "AIU – Perímetro Geral (Setor Central e demais)",
    fillColor: "#0d9488",
    fillOpacity: 0.1,
    strokeColor: "#0f766e",
    strokeWeight: 2,
    maxFeatures: 50,
  },
  {
    id: "perimetro_especial_aiu",
    typeName: "perimetro_especial_aiu",
    label: "AIU – Perímetro Especial",
    fillColor: "#14b8a6",
    fillOpacity: 0.1,
    strokeColor: "#0d9488",
    strokeWeight: 1.5,
    maxFeatures: 50,
  },
  {
    id: "aiu_vila_leopoldina",
    typeName: "aiu_vl_perimetro_adesao",
    label: "AIU Vila Leopoldina – Perímetro Adesão",
    fillColor: "#0f766e",
    fillOpacity: 0.12,
    strokeColor: "#115e59",
    strokeWeight: 1.5,
    maxFeatures: 100,
  },
  {
    id: "aiu_jurubatuba",
    typeName: "aiu_perimetro_jurubatuba",
    label: "AIU Arco Jurubatuba",
    fillColor: "#0891b2",
    fillOpacity: 0.1,
    strokeColor: "#0e7490",
    strokeWeight: 1.5,
    maxFeatures: 50,
  },
  {
    id: "aiu_pinheiros",
    typeName: "aiu_perimetro_pinheiros",
    label: "AIU Arco Pinheiros",
    fillColor: "#06b6d4",
    fillOpacity: 0.1,
    strokeColor: "#0891b2",
    strokeWeight: 1.5,
    maxFeatures: 50,
  },
  // Requalifica Centro
  {
    id: "requalifica_centro",
    typeName: "requalifica_centro_perimetro_geral",
    label: "Requalifica Centro (Lei 17.577/21)",
    fillColor: "#4f46e5",
    fillOpacity: 0.12,
    strokeColor: "#4338ca",
    strokeWeight: 2,
    maxFeatures: 50,
  },
  // Instrumentos urbanísticos
  {
    id: "outorga_onerosa",
    typeName: "outorga_onerosa",
    label: "Outorga Onerosa",
    fillColor: "#ea580c",
    fillOpacity: 0.15,
    strokeColor: "#c2410c",
    strokeWeight: 1,
    maxFeatures: 200,
  },
  {
    id: "imovel_notificado",
    typeName: "imovel_notificado",
    label: "Imóveis Notificados – Função Social",
    fillColor: "#16a34a",
    fillOpacity: 0.2,
    strokeColor: "#15803d",
    strokeWeight: 1,
    maxFeatures: 300,
  },
  {
    id: "restricao_geotecnica",
    typeName: "restricao_geotecnica",
    label: "Áreas com Restrições Geotécnicas",
    fillColor: "#78350f",
    fillOpacity: 0.15,
    strokeColor: "#a16207",
    strokeWeight: 1,
    maxFeatures: 200,
  },
  // Desapropriação (item 21)
  {
    id: "planta_dup_dis",
    typeName: "planta_dup_dis_pd",
    label: "Plantas de Decreto (DUP / DIS)",
    fillColor: "#2563eb",
    fillOpacity: 0.12,
    strokeColor: "#1d4ed8",
    strokeWeight: 1,
    maxFeatures: 150,
  },
  {
    id: "planta_expropriatoria",
    typeName: "planta_expropriatoria_pd",
    label: "Plantas Expropriatórias",
    fillColor: "#1f2937",
    fillOpacity: 0.12,
    strokeColor: "#111827",
    strokeWeight: 1,
    maxFeatures: 150,
  },
  {
    id: "planta_expropriatoria_indireta",
    typeName: "planta_expropriatoria_indireta_pd",
    label: "Plantas Expropriatórias Indiretas",
    fillColor: "#78350f",
    fillOpacity: 0.12,
    strokeColor: "#a16207",
    strokeWeight: 1,
    maxFeatures: 150,
  },
  // Licenciamento / Licenciamento Ambiental (item 16)
  {
    id: "licenca_expedida",
    typeName: "GEOSAMPA_licenca_expedida_multipoligono_internet",
    label: "Licença Expedida (multipolígono)",
    fillColor: "#6366f1",
    fillOpacity: 0.1,
    strokeColor: "#4f46e5",
    strokeWeight: 1,
    maxFeatures: 300,
  },
  {
    id: "licenca_obra",
    typeName: "GEOSAMPA_licenca_obra",
    label: "Licença de Obra",
    fillColor: "#7c3aed",
    fillOpacity: 0.12,
    strokeColor: "#6d28d9",
    strokeWeight: 1,
    maxFeatures: 200,
  },
  {
    id: "licenca_industrial",
    typeName: "licenca_industrial",
    label: "Licença Ambiental (industrial)",
    fillColor: "#dc2626",
    fillOpacity: 0.12,
    strokeColor: "#b91c1c",
    strokeWeight: 1,
    maxFeatures: 150,
  },
  {
    id: "estacao_radio_base",
    typeName: "estacao_radio_base",
    label: "Estação Rádio Base – Termo de Adesão",
    fillColor: "#2563eb",
    fillOpacity: 0.2,
    strokeColor: "#1d4ed8",
    strokeWeight: 1,
    maxFeatures: 200,
  },
  {
    id: "area_contaminada_sigac",
    typeName: "GEOSAMPA_area_contaminada_sigac",
    label: "Área Contaminada / Suspeita (SIGAC)",
    fillColor: "#b91c1c",
    fillOpacity: 0.2,
    strokeColor: "#991b1b",
    strokeWeight: 1.5,
    maxFeatures: 150,
  },
  {
    id: "area_contaminada_reabilitada",
    typeName: "area_contaminada_reabilitada_svma",
    label: "Área Contaminada e Reabilitada",
    fillColor: "#16a34a",
    fillOpacity: 0.15,
    strokeColor: "#15803d",
    strokeWeight: 1,
    maxFeatures: 100,
  },
  {
    id: "termo_compromisso_ambiental",
    typeName: "GEOSAMPA_termo_compromisso_ambiental",
    label: "Termo de Compromisso Ambiental (APP)",
    fillColor: "#15803d",
    fillOpacity: 0.15,
    strokeColor: "#166534",
    strokeWeight: 1,
    maxFeatures: 150,
  },
  // Limpeza Urbana (item 17) – overlays
  {
    id: "servico_divisivel_agrupamento",
    typeName: "servico_divisivel_agrupamento",
    label: "Agrupamento Serviços Divisíveis",
    fillColor: "#22c55e",
    fillOpacity: 0.12,
    strokeColor: "#16a34a",
    strokeWeight: 1,
    maxFeatures: 200,
  },
  {
    id: "servico_varricao_lote",
    typeName: "servico_varricao_lote_amlurb",
    label: "Serviços de Varrição e Limpeza (lote AMLURB)",
    fillColor: "#84cc16",
    fillOpacity: 0.12,
    strokeColor: "#65a30d",
    strokeWeight: 1,
    maxFeatures: 300,
  },
  {
    id: "papeleira",
    typeName: "papeleira",
    label: "Papeleira",
    fillColor: "#38bdf8",
    fillOpacity: 0.25,
    strokeColor: "#0ea5e9",
    strokeWeight: 1,
    maxFeatures: 500,
  },
  {
    id: "patio_compostagem",
    typeName: "patio_compostagem",
    label: "Pátio de Compostagem",
    fillColor: "#16a34a",
    fillOpacity: 0.2,
    strokeColor: "#15803d",
    strokeWeight: 1.5,
    maxFeatures: 50,
  },
  {
    id: "aterro_rcc",
    typeName: "aterro_rcc",
    label: "Aterro RCC (resíduos construção)",
    fillColor: "#78716c",
    fillOpacity: 0.2,
    strokeColor: "#57534e",
    strokeWeight: 1,
    maxFeatures: 50,
  },
  {
    id: "ponto_revitalizado",
    typeName: "ponto_revitalizado",
    label: "Ponto Revitalizado",
    fillColor: "#22c55e",
    fillOpacity: 0.25,
    strokeColor: "#16a34a",
    strokeWeight: 1,
    maxFeatures: 150,
  },
  // Cadastro fiscal (item 7 – dados fiscais, lote, IPTU)
  {
    id: "setor_fiscal",
    typeName: "setor_fiscal",
    label: "Cadastro Fiscal – Setor",
    fillColor: "#0ea5e9",
    fillOpacity: 0.08,
    strokeColor: "#0284c7",
    strokeWeight: 1,
    maxFeatures: 500,
  },
  {
    id: "quadra_fiscal",
    typeName: "quadra_fiscal",
    label: "Cadastro Fiscal – Quadra",
    fillColor: "#eab308",
    fillOpacity: 0.1,
    strokeColor: "#ca8a04",
    strokeWeight: 1,
    maxFeatures: 800,
  },
  {
    id: "lote_cidadao",
    typeName: "lote_cidadao",
    label: "Cadastro Fiscal – Lote",
    fillColor: "#84cc16",
    fillOpacity: 0.12,
    strokeColor: "#65a30d",
    strokeWeight: 1,
    maxFeatures: 1000,
  },
  {
    id: "zona_fiscal",
    typeName: "zona_fiscal",
    label: "Cadastro Fiscal – Zona Fiscal",
    fillColor: "#6366f1",
    fillOpacity: 0.1,
    strokeColor: "#4f46e5",
    strokeWeight: 1.5,
    maxFeatures: 200,
  },
  // Área Pública
  {
    id: "area_cedida",
    typeName: "GEOSAMPA_area_cedida_cidadao",
    label: "Área Pública – Área Cedida",
    fillColor: "#a855f7",
    fillOpacity: 0.12,
    strokeColor: "#9333ea",
    strokeWeight: 1,
    maxFeatures: 300,
  },
  {
    id: "cadastro_area_publica",
    typeName: "GEOSAMPA_cadastro_area_publica_cidadao",
    label: "Área Pública – Cadastro de Área Pública",
    fillColor: "#c084fc",
    fillOpacity: 0.1,
    strokeColor: "#a855f7",
    strokeWeight: 1,
    maxFeatures: 400,
  },
  // Parcelamento
  {
    id: "passagem_ps",
    typeName: "passagem",
    label: "Parcelamento – Passagem (PS)",
    fillColor: "#0ea5e9",
    fillOpacity: 0.1,
    strokeColor: "#0284c7",
    strokeWeight: 1,
    maxFeatures: 500,
  },
  {
    id: "diretriz_dz",
    typeName: "diretriz",
    label: "Parcelamento – Diretriz (DZ)",
    fillColor: "#f97316",
    fillOpacity: 0.12,
    strokeColor: "#ea580c",
    strokeWeight: 1,
    maxFeatures: 400,
  },
  {
    id: "desmembramento_gleba",
    typeName: "desmembramento_gleba",
    label: "Parcelamento – Desmembramento de Gleba",
    fillColor: "#ec4899",
    fillOpacity: 0.12,
    strokeColor: "#db2777",
    strokeWeight: 1,
    maxFeatures: 300,
  },
  {
    id: "conjunto_cj",
    typeName: "conjunto",
    label: "Parcelamento – Conjunto (CJ)",
    fillColor: "#78716c",
    fillOpacity: 0.1,
    strokeColor: "#57534e",
    strokeWeight: 1,
    maxFeatures: 300,
  },
  {
    id: "cartorio_registro_imovel",
    typeName: "cartorio_registro_imovel",
    label: "Parcelamento – Cartórios de Registro de Imóveis",
    fillColor: "#fda4af",
    fillOpacity: 0.2,
    strokeColor: "#fb7185",
    strokeWeight: 1,
    maxFeatures: 100,
  },
];

export function buildWfsUrl(layer: GeoSampaOverlayLayer): string {
  const max = layer.maxFeatures ?? 500;
  const sep = WFS_BASE.includes("?") ? "&" : "?";
  return `${WFS_BASE}${sep}typeName=geoportal:${layer.typeName}&maxFeatures=${max}`;
}
