-- Reinserir audiência de teste apenas para evidência (print).
-- Mesmo conteúdo do mock original; remover após captura.
INSERT INTO public.audiencias (
  splegis_chave,
  titulo,
  descricao,
  data,
  hora,
  local,
  tema,
  status,
  comissao,
  vagas_disponiveis,
  inscricoes_abertas,
  link_transmissao,
  projeto_referencia,
  projeto_autores,
  projetos,
  observacao,
  convidados,
  mais_informacoes
) VALUES (
  'TESTE-MOCK-16H05',
  'Audiência: [TESTE] Mock 14h – validação lembrete 1h (disparo 13h)',
  'Audiência fictícia para testar o lembrete 1 hora antes. Pode ignorar.',
  CURRENT_DATE,
  '14:00:00',
  'Sala de teste (mock)',
  'Validação de cron',
  'agendada',
  '[TESTE] Mock 14h',
  NULL,
  true,
  NULL,
  NULL,
  NULL,
  '[]'::jsonb,
  'Lembrete de teste: disparar cron às 13h para validar notificação 1h antes (audiência 14h).',
  NULL,
  NULL
)
ON CONFLICT (splegis_chave) DO UPDATE SET
  data = CURRENT_DATE,
  hora = '14:00:00',
  titulo = EXCLUDED.titulo,
  descricao = EXCLUDED.descricao,
  status = EXCLUDED.status,
  observacao = EXCLUDED.observacao,
  comissao = EXCLUDED.comissao,
  updated_at = now();

-- Mock para evidência do lembrete D-1 (24h antes): amanhã às 14h00.
INSERT INTO public.audiencias (
  splegis_chave,
  titulo,
  descricao,
  data,
  hora,
  local,
  tema,
  status,
  comissao,
  vagas_disponiveis,
  inscricoes_abertas,
  link_transmissao,
  projeto_referencia,
  projeto_autores,
  projetos,
  observacao,
  convidados,
  mais_informacoes
) VALUES (
  'TESTE-MOCK-D1-14H00',
  'Audiência: [TESTE] Mock amanhã 14h – validação lembrete D-1',
  'Audiência fictícia para testar o lembrete 24h antes (D-1). Pode ignorar.',
  CURRENT_DATE + 1,
  '14:00:00',
  'Sala de teste (mock D-1)',
  'Validação de cron',
  'agendada',
  '[TESTE] Mock D-1 14h',
  NULL,
  true,
  NULL,
  NULL,
  NULL,
  '[]'::jsonb,
  'Lembrete de teste: chamar audiencia-reminder-d1 com for_date=amanhã para notificação D-1 (audiência 14h).',
  NULL,
  NULL
)
ON CONFLICT (splegis_chave) DO UPDATE SET
  data = CURRENT_DATE + 1,
  hora = '14:00:00',
  titulo = EXCLUDED.titulo,
  descricao = EXCLUDED.descricao,
  status = EXCLUDED.status,
  observacao = EXCLUDED.observacao,
  comissao = EXCLUDED.comissao,
  updated_at = now();
