// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// New standardized env names (preferred):
// - CAMARA_URL
// - CAMARA_PUBLISHABLE_KEY
//
// Backward compatibility (temporary):
// - VITE_SUPABASE_URL
// - VITE_SUPABASE_PUBLISHABLE_KEY
const SUPABASE_URL =
  import.meta.env.CAMARA_URL ?? import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.CAMARA_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Exportados para chamadas que precisam da anon key (ex.: complete-registration pós-cadastro sem sessão)
export const supabaseUrl = SUPABASE_URL;
export const supabaseAnonKey = SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});